### ISSUE TITLE
Provide more Information when x86_energy_init_architecture_nodes() fails

### ISSUE THREAD

**Issue by AndreasGocht** [tud-zih-energy/x86_energy#3]
There are several cases when the call to `x86_energy_init_architecture_nodes()` might fail, and NULL is returned. Please add some way to get an information why it failed.

Best,

Andreas

**Comment by Quimoniz** [comment]
Thanks to @rschoene this should be taken care of with the [latest commit](https://github.com/tud-zih-energy/x86_energy/commit/56621e8c9b7550ad0e20e2b656dfc0369bb1a8ef)

If you still happen to find any error case where no error message is being stored to `error_string`/`x86_energy_error_string()` I would be more than happy to hear about it

**Comment by rschoene** [comment]
@AndreasGocht Can this be closed?

**Comment by AndreasGocht** [comment]
think so.
